#define QUT "QUT"
#define PLG "PLG"
#define RLG "RLG"
#define OK "OK"
#define WIN "WIN"
#define DUP "DUP"
#define NOK "NOK"
#define OVR "OVR"
#define INV "INV"
#define ERR "ERR"
#define RSG "RSG"
#define REV "REV"
#define SNG "SNG"
#define PWG "PWG"
#define RQT "RQT"
#define RWG "RWG"
#define GSB "GSB"
#define RSB "RSB"
#define EMPTY "EMPTY"
#define GHL "GHL"
#define RHL "RHL"
#define STA "STA"
#define RST "RST"
#define FIN "FIN"
#define ACT "ACT"
#define Q 'Q'
#define F 'F'
#define W 'W'
#define T "T"
#define G "G"
#define LINE_SIZE 32
#define FINISHEd_GAME_PATH_SIZE 36

#define GAMES_DIR "GAMES/"
#define COPY "cp "
#define MOVE "mv "
#define ACTIVE_GAME_PATH "GAMES/GAME_"
#define SCORES "SCORES/"
#define STATE "STATE_"
#define TXT ".txt"
#define LAST_GAME_MSG "Last finalized game for player "
#define ACTIVE_GAME_FOUND "Active game found for player "
#define TRANSACTIONS_MSG " Transactions found: "
#define LETTER_TRIAL "Letter trial: "
#define TERMINATION "Termination: "
#define WORD_GUESS "Word guess: "
#define CURRENTLY_SOLVED "Solved so far: "

#define FALSE 0
#define TRUE 1
